---
- hosts: dynqatesting.com
  tasks:

    - include_tasks: ../../server_ready.yml

    - name: Install munin
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "munin"
        - "munin-node"

    - name: Copy munin.conf
      copy:
        src: munin.conf
        dest: /etc/munin/munin.conf
        mode: 0644

    - name: Create munin monitor config
      template:
        src: munin-conf.d/monitor-host.conf.j2
        dest: /etc/munin/munin-conf.d/monitor-host.conf
        mode: 0644

    - name: restart munin
      service:
        name: munin-node
        enabled: yes
        state: restarted
