---
- hosts: beantownpub.com
  tasks:

    - name: pull latest code from git repo
      command: git pull origin
      args:
        chdir: /code/production/jal

    - name: Create Beantown container
      docker_container:
        name: beantown
        image: jalgraves/jal_django:0.0.1
        restart_policy: unless-stopped
        state: started
        entrypoint: "/bin/sh entrypoint.sh"
        exposed_ports:
          - 8000
        volumes:
          - /code/entrypoint.sh:/app/entrypoint.sh
          - /code/production/jal/dist/beantown:/app
          - /code/production/jal/dist/beantown/static:/static
          - /code/production/jal/dist/beantown/dbbackups/:/var/db_backups
        networks:
          - name: bridge
          - name: backend
        env:
            EVENTFUL_API_KEY: "{{ lookup('env', 'EVENTFUL_API_KEY') }}"
            JAL_BEANTOWN_REQUESTS_GMAIL_PASSWORD: "{{ lookup('env', 'JAL_BEANTOWN_REQUESTS_GMAIL_PASSWORD') }}"
            JAL_TWILIO_SID: "{{ lookup('env', 'JAL_TWILIO_SID') }}"
            JAL_TWILIO_TOKEN: "{{ lookup('env', 'JAL_TWILIO_TOKEN') }}"
            JAL_SLACK_WEBHOOK_URL: "{{ lookup('env', 'JAL_SLACK_WEBHOOK_URL') }}"
            SITE_NAME: "beantown"
            LOGSTASH_HOST: "logstash.backend:9600"
            LOGSTASH_PATH: "/app/log/*.log"
