---
- hosts: beantownpub.com
  tasks:

    - name: pull latest code from git repo
      command: git pull origin
      args:
        chdir: /code/production/jal

    - name: Create Doc's container
      docker_container:
        name: drdavisicecream
        image: jalgraves/jal_debian:latest
        restart_policy: unless-stopped
        state: started
        restart: yes
        entrypoint: "/bin/sh entrypoint.sh"
        exposed_ports:
          - 8000
        volumes:
          - /code/production/jal/dist/drdavisicecream:/app
        networks:
          - name: bridge
          - name: backend
        env:
            SITE_NAME: "drdavisicecream"
            LOGSTASH_HOST: "logstash.backend:9600"
            LOGSTASH_PATH: "/app/log/*.log"
