---
- hosts: 68.183.144.128
  tasks:

    - name: Check for docker network
      shell: docker network list
      register: docker_nets

    - name: create docker backend network
      command: docker network create backend --subnet=192.168.42.0/24 --gateway=192.168.42.1 --ip-range=192.168.42.0/24
      when: docker_nets.stdout.find(' backend') == -1

    # - name: Copy NGINX files
    #   copy: src=nginx/conf/jalgraves.conf dest=/root/ansible/nginx/
  

    - name: pull latest code from git repo
      command: git pull origin
      args:
        chdir: /code/repos/production/jal

    - name: Create jalgraves container
      docker_container:
        name: jalgraves
        image: jalgraves/jal_pandas:0.0.2
        restart_policy: unless-stopped
        state: started
        entrypoint: "/bin/sh entrypoint.sh"
        exposed_ports:
          - 8000
        volumes:
          - /code/repos/production/jal/dist/jalgraves:/app
          - /code/repos/production/jal/dist/jalgraves/static:/static
          - /code/repos/production/jal/dist/jalgraves/dbbackups/:/var/db_backups
        networks:
          - name: bridge
          - name: backend
        env:
            JAL_SLACK_WEBHOOK_URL: "{{ lookup('env', 'JAL_SLACK_WEBHOOK_URL') }}"
