---
- hosts: beantownpub.com
  tasks:

    - name: Check for docker network
      shell: docker network list
      register: docker_nets

    - name: create docker backend network
      command: docker network create backend --subnet=192.168.42.0/24 --gateway=192.168.42.1 --ip-range=192.168.42.0/24
      when: docker_nets.stdout.find(' backend') == -1

    - name: pull latest code from git repo
      command: git pull origin
      args:
        chdir: /code/production/jal

    - name: Build Wavelength's image
      docker_image:
        path: /code/production/jal/dist/wavelengths
        name: wavelengths_image
        state: present
        force: yes
        tag: latest

    - name: Create Wavelengts container
      docker_container:
        name: wavelengths
        image: wavelengths_image:latest
        restart_policy: unless-stopped
        state: started
        entrypoint: "/bin/sh entrypoint.sh"
        exposed_ports:
          - 8000
        volumes:
          - /code/production/jal/dist/wavelengths/dist/static:/static
        networks:
          - name: bridge
          - name: backend
        env:
            JAL_SLACK_WEBHOOK_URL: "{{ lookup('env', 'JAL_SLACK_WEBHOOK_URL') }}"
