---
- hosts: beantownpub.com
  tasks:

    - name: pull latest code from git repo
      command: git pull origin
      args:
        chdir: /code/production/jal

    - name: Create  Ziggys container
      docker_container:
        name: ziggys
        image: jalgraves/jal_debian:latest
        restart_policy: unless-stopped
        state: started
        entrypoint: "/bin/sh entrypoint.sh"
        exposed_ports:
          - 8000
        volumes:
          - /code/production/jal/dist/ziggys:/app
          - /code/production/jal/dist/ziggys/static:/static
        networks:
          - name: bridge
          - name: backend
        env:
            JAL_BEANTOWN_REQUESTS_GMAIL_PASSWORD: "{{ lookup('env', 'JAL_BEANTOWN_REQUESTS_GMAIL_PASSWORD') }}"
            JAL_SLACK_WEBHOOK_URL: "{{ lookup('env', 'JAL_SLACK_WEBHOOK_URL') }}"
            SITE_NAME: "ziggys"
            LOGSTASH_HOST: "logstash.backend:9600"
            LOGSTASH_PATH: "/app/log/*.log"
