---
- import_playbook: remove.yml

- hosts: dynqatesting.com
  tasks:

    - include_tasks: ../../server_ready.yml

    - name: Apt purge fail2ban
      apt:
        name: fail2ban
        state: absent
        purge: yes

    - name: Remove fail2ban config
      file:
        path: /etc/fail2ban
        state: absent
